Fix CMake transient dependency for XGandalf
Without this, other CMake targets that are built using libcrystfel
appear to fail with exported symbol errors, because they do not
transitively link to XGandalf e.g.:

    libcrystfel/libcrystfel.so.0.10.0: undefined reference to `IndexerPlain_delete'
    libcrystfel/libcrystfel.so.0.10.0: undefined reference to `IndexerPlain_index'